$root_path = "../.."
$node_modules = "#{$root_path}/node_modules"
$react_native_path = "#{$node_modules}/react-native"

require_relative "#{$node_modules}/react-native/scripts/react_native_pods"

platform :ios, "11.0"

target "SafeAreaViewExample" do
  use_react_native!(
    :path => $react_native_path,
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # use_flipper!()

  pod "react-native-safe-area-context", :path => $root_path
  pod "RNCAsyncStorage", :path => "#{$node_modules}/@react-native-community/async-storage"
  pod "RNCMaskedView", :path => "#{$node_modules}/@react-native-community/masked-view"
  pod "RNGestureHandler", :path => "#{$node_modules}/react-native-gesture-handler"
  pod "RNReanimated", :path => "#{$node_modules}/react-native-reanimated"
  pod "RNScreens", :path => "#{$node_modules}/react-native-screens"

  post_install do |installer|
    react_native_post_install(installer)
  end
end

